const layer = (id, type, name, x, y, width, height, color, extra = {}) => ({
  id,
  type,
  name,
  x,
  y,
  width,
  height,
  color,
  opacity: 1,
  rotation: 0,
  fontFamily: "Arial",
  fontWeight: "800",
  fontSize: 0.08,
  align: "left",
  textSlot: "literal",
  text: "",
  strokeColor: "#000000",
  strokeWidth: 0,
  spacing: 0.08,
  src: "",
  ...extra,
});
export const seed = () => [
  {
    id: "joacoavia",
    owner_email: "system",
    status: "published",
    definition: {
      name: "JoacoAvia · Grid + Topografía",
      network: "JoacoAvia",
      format: "vertical",
      status: "published",
      background: "#0b0b0b",
      safeArea: { left: 0.09, top: 0.09, right: 0.1, bottom: 0.18 },
      layers: [
        layer("grid", "grid", "Malla", 0.06, 0.06, 0.88, 0.5, "#ffffff", {
          opacity: 0.07,
        }),
        layer("title", "text", "Título", 0.09, 0.12, 0.82, 0.22, "#eaeaea", {
          textSlot: "title",
          fontFamily: "Bebas Neue, Oswald, Arial",
          fontSize: 0.13,
          strokeWidth: 0.002,
        }),
        layer(
          "subtitle",
          "text",
          "Subtítulo",
          0.09,
          0.36,
          0.72,
          0.12,
          "#c8a96a",
          { textSlot: "subtitle", fontFamily: "Georgia", fontSize: 0.065 },
        ),
        layer(
          "topo",
          "topography",
          "Topografía",
          0.62,
          0.65,
          0.33,
          0.25,
          "#c8a96a",
          { opacity: 0.25 },
        ),
      ],
    },
  },
  {
    id: "youtube",
    owner_email: "system",
    status: "published",
    definition: {
      name: "YouTube · Impacto",
      network: "YouTube",
      format: "horizontal",
      status: "published",
      background: "#0d1117",
      safeArea: { left: 0.12, top: 0.12, right: 0.12, bottom: 0.12 },
      layers: [
        layer("yt-title", "text", "Título", 0.12, 0.28, 0.76, 0.25, "#ffffff", {
          textSlot: "title",
          fontSize: 0.13,
          align: "center",
          strokeWidth: 0.008,
        }),
        layer(
          "yt-sub",
          "text",
          "Subtítulo",
          0.18,
          0.58,
          0.64,
          0.12,
          "#ffd34d",
          { textSlot: "subtitle", fontSize: 0.065, align: "center" },
        ),
      ],
    },
  },
  {
    id: "tiktok",
    owner_email: "system",
    status: "published",
    definition: {
      name: "TikTok / Reels · Limpio",
      network: "TikTok",
      format: "vertical",
      status: "published",
      background: "#1e2430",
      safeArea: { left: 0.1, top: 0.1, right: 0.16, bottom: 0.18 },
      layers: [
        layer("tk-title", "text", "Título", 0.1, 0.28, 0.74, 0.24, "#f5f7fb", {
          textSlot: "title",
          fontSize: 0.1,
        }),
        layer("tk-sub", "text", "Subtítulo", 0.1, 0.59, 0.7, 0.14, "#73d2de", {
          textSlot: "subtitle",
          fontSize: 0.052,
        }),
      ],
    },
  },
  {
    id: "instagram",
    owner_email: "system",
    status: "published",
    definition: {
      name: "Instagram · Premium",
      network: "Instagram",
      format: "square",
      status: "published",
      background: "#12100e",
      safeArea: { left: 0.12, top: 0.12, right: 0.12, bottom: 0.12 },
      layers: [
        layer("ig-title", "text", "Título", 0.12, 0.3, 0.76, 0.22, "#f6f1e8", {
          textSlot: "title",
          fontFamily: "Georgia",
          fontSize: 0.095,
          align: "center",
        }),
        layer(
          "ig-sub",
          "text",
          "Subtítulo",
          0.17,
          0.57,
          0.66,
          0.14,
          "#e7b66b",
          {
            textSlot: "subtitle",
            fontFamily: "Georgia",
            fontSize: 0.05,
            align: "center",
          },
        ),
      ],
    },
  },
];
