const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const allowed=new Set(['keanuavia@gmail.com','r.labbe.a@gmail.com','admin@aviarockets.cl']);
let sessionUser={};try{sessionUser=JSON.parse(localStorage.getItem('avia_auth_user')||'{}')}catch{};
const userEmail=String(sessionUser.email||'').toLowerCase();
if(!localStorage.getItem('avia_auth_token')||!allowed.has(userEmail)){location.replace(`login.html?next=${encodeURIComponent('portada.html')}`);throw Error('Acceso no habilitado')}
const email=$('#email');email.textContent=userEmail;
const layer=(id,type,name,x,y,width,height,color,extra={})=>({id,type,name,x,y,width,height,color,opacity:1,rotation:0,fontFamily:'Arial',fontWeight:'800',fontSize:.08,align:'left',textSlot:'literal',text:'',strokeColor:'#000000',strokeWidth:0,spacing:.08,src:'',...extra});
const seed=()=>[
 {id:'joacoavia',owner_email:'system',status:'published',definition:{name:'JoacoAvia · Grid + Topografía',network:'JoacoAvia',format:'vertical',status:'published',background:'#0b0b0b',safeArea:{left:.09,top:.09,right:.1,bottom:.18},layers:[layer('grid','grid','Malla',.06,.06,.88,.5,'#ffffff',{opacity:.07}),layer('title','text','Título',.09,.12,.82,.22,'#eaeaea',{textSlot:'title',fontFamily:'Bebas Neue, Oswald, Arial',fontSize:.13,strokeWidth:.002}),layer('subtitle','text','Subtítulo',.09,.36,.72,.12,'#c8a96a',{textSlot:'subtitle',fontFamily:'Georgia',fontSize:.065}),layer('topo','topography','Topografía',.62,.65,.33,.25,'#c8a96a',{opacity:.25})]}},
 {id:'youtube',owner_email:'system',status:'published',definition:{name:'YouTube · Impacto',network:'YouTube',format:'horizontal',status:'published',background:'#0d1117',safeArea:{left:.12,top:.12,right:.12,bottom:.12},layers:[layer('yt-title','text','Título',.12,.28,.76,.25,'#ffffff',{textSlot:'title',fontSize:.13,align:'center',strokeWidth:.008}),layer('yt-sub','text','Subtítulo',.18,.58,.64,.12,'#ffd34d',{textSlot:'subtitle',fontSize:.065,align:'center'})]}},
 {id:'tiktok',owner_email:'system',status:'published',definition:{name:'TikTok / Reels · Limpio',network:'TikTok',format:'vertical',status:'published',background:'#1e2430',safeArea:{left:.1,top:.1,right:.16,bottom:.18},layers:[layer('tk-title','text','Título',.1,.28,.74,.24,'#f5f7fb',{textSlot:'title',fontSize:.1}),layer('tk-sub','text','Subtítulo',.1,.59,.7,.14,'#73d2de',{textSlot:'subtitle',fontSize:.052})]}},
 {id:'instagram',owner_email:'system',status:'published',definition:{name:'Instagram · Premium',network:'Instagram',format:'square',status:'published',background:'#12100e',safeArea:{left:.12,top:.12,right:.12,bottom:.12},layers:[layer('ig-title','text','Título',.12,.3,.76,.22,'#f6f1e8',{textSlot:'title',fontFamily:'Georgia',fontSize:.095,align:'center'}),layer('ig-sub','text','Subtítulo',.17,.57,.66,.14,'#e7b66b',{textSlot:'subtitle',fontFamily:'Georgia',fontSize:.05,align:'center'})]}}
];
const storageKey=`avia_portada_profiles_v1:${userEmail}`;
const readProfiles=()=>{const saved=localStorage.getItem(storageKey);return saved?JSON.parse(saved):seed()};
const writeProfiles=p=>localStorage.setItem(storageKey,JSON.stringify(p));
const api=async(url,opts={})=>{let rows=readProfiles(),method=opts.method||'GET',body=opts.body?JSON.parse(opts.body):{};if(url==='/api/session')return{email:userEmail,enabled:true};if(url==='/api/profiles'&&method==='GET')return rows;if(url==='/api/profiles'&&method==='POST'){const id=crypto.randomUUID(),row={id,owner_email:userEmail,status:body.status,definition:body};rows.unshift(row);writeProfiles(rows);return{id,...body}};const id=url.split('/')[3],i=rows.findIndex(x=>x.id===id);if(url.endsWith('/duplicate')){const copy=structuredClone(rows[i]);copy.id=crypto.randomUUID();copy.owner_email=userEmail;copy.definition.name+=' · copia';copy.definition.status=copy.status='draft';rows.unshift(copy);writeProfiles(rows);return copy}if(method==='PUT'){rows[i]={id,owner_email:rows[i]?.owner_email||userEmail,status:body.status,definition:body};writeProfiles(rows);return{id,...body}}if(method==='DELETE'){if(rows[i]?.owner_email==='system')throw Error('Duplica el perfil inicial antes de borrarlo');rows.splice(i,1);writeProfiles(rows);return null}if(url==='/api/exports')return{ok:true};throw Error('Operación no válida')};
let profiles=[],current,selected=null,texts={title:'START BROKEN.',subtitle:'finish sharp'};
const canvas=$('#canvas'),ctx=canvas.getContext('2d'),cc=$('#configCanvas'),cctx=cc.getContext('2d');
$$('nav button').forEach(b=>b.onclick=()=>{$$('nav button,.tab').forEach(x=>x.classList.remove('active'));b.classList.add('active');$('#'+b.dataset.tab).classList.add('active');drawAll()});
$('#title').oninput=e=>{texts.title=e.target.value;drawAll()}; $('#subtitle').oninput=e=>{texts.subtitle=e.target.value;drawAll()}; $('#guides').onchange=drawAll;
$('#profile').onchange=e=>selectProfile(e.target.value); $('#format').onchange=e=>{current.format=e.target.value;drawAll()};
function fit(c,format){const s={vertical:[1080,1920],horizontal:[1280,720],square:[1080,1080]}[format];c.width=s[0];c.height=s[1]}
function render(c,x,p,guides=true){fit(c,p.format);x.fillStyle=p.background;x.fillRect(0,0,c.width,c.height);for(const l of p.layers) drawLayer(x,c,l);if(guides){const s=p.safeArea;x.save();x.strokeStyle='#ff5b45';x.lineWidth=Math.max(3,c.width*.003);x.setLineDash([18,12]);x.strokeRect(s.left*c.width,s.top*c.height,(1-s.left-s.right)*c.width,(1-s.top-s.bottom)*c.height);x.restore()}if(selected){const l=p.layers.find(v=>v.id===selected);if(l){x.strokeStyle='#4ee3ff';x.lineWidth=4;x.strokeRect(l.x*c.width,l.y*c.height,l.width*c.width,l.height*c.height);x.fillStyle='#4ee3ff';x.fillRect((l.x+l.width)*c.width-12,(l.y+l.height)*c.height-12,24,24)}}}
function drawLayer(x,c,l){x.save();x.globalAlpha=l.opacity??1;const X=l.x*c.width,Y=l.y*c.height,W=l.width*c.width,H=l.height*c.height;x.translate(X+W/2,Y+H/2);x.rotate((l.rotation||0)*Math.PI/180);x.translate(-W/2,-H/2);x.fillStyle=l.color;if(l.type==='rect')x.fillRect(0,0,W,H);if(l.type==='line')x.fillRect(0,H/2,W,Math.max(2,H));if(l.type==='grid'){x.strokeStyle=l.color;x.lineWidth=1;for(let i=0;i<=1;i+=l.spacing){x.beginPath();x.moveTo(i*W,0);x.lineTo(i*W,H);x.stroke();x.beginPath();x.moveTo(0,i*H);x.lineTo(W,i*H);x.stroke()}}if(l.type==='topography'){x.strokeStyle=l.color;for(let i=1;i<9;i++){x.beginPath();x.ellipse(W,H,W*i/10,H*i/10,0,Math.PI,Math.PI*1.5);x.stroke()}}if(l.type==='image'&&l.src){const im=new Image();im.onload=()=>{x.drawImage(im,0,0,W,H);drawAll()};im.src=l.src}if(l.type==='text'){const value=l.textSlot==='title'?texts.title:l.textSlot==='subtitle'?texts.subtitle:l.text;x.font=`${l.fontWeight} ${Math.round(l.fontSize*c.height)}px ${l.fontFamily}`;x.textAlign=l.align;x.textBaseline='top';const ax=l.align==='center'?W/2:l.align==='right'?W:0;x.lineJoin='round';if(l.strokeWidth){x.strokeStyle=l.strokeColor;x.lineWidth=l.strokeWidth*c.width;x.strokeText(value,ax,0,W)}x.fillText(value,ax,0,W)}x.restore()}
function drawAll(){if(!current)return;render(canvas,ctx,{...current,format:$('#format').value},$('#guides').checked);render(cc,cctx,current,true)}
function selectProfile(id){const row=profiles.find(p=>p.id===id);if(!row)return;current=structuredClone(row.definition);current.id=row.id;selected=null;$('#format').value=current.format;fillConfig();drawAll()}
function fillConfig(){if(!current)return;$('#cfgName').value=current.name;$('#cfgNetwork').value=current.network;$('#cfgFormat').value=current.format;$('#cfgStatus').value=current.status;$('#cfgBackground').value=current.background;for(const k of ['Left','Top','Right','Bottom'])$('#safe'+k).value=Math.round(current.safeArea[k.toLowerCase()]*100);renderLayers()}
function renderLayers(){const box=$('#cfgLayers');box.innerHTML='';current.layers.forEach(l=>{const d=document.createElement('div');d.className='layer '+(selected===l.id?'selected':'');const textFields=l.type==='text'?`<label>Tipografía<input data-k="fontFamily" data-raw value="${esc(l.fontFamily)}"></label><label>Contenido<select data-k="textSlot" data-raw><option value="title">Título del editor</option><option value="subtitle">Subtítulo del editor</option><option value="literal">Texto fijo</option></select></label><label>Texto fijo<input data-k="text" data-raw value="${esc(l.text)}"></label>`:'';const imageField=l.type==='image'?`<label>Imagen/logo<input data-file type="file" accept="image/png,image/jpeg,image/webp,image/svg+xml"></label>`:'';d.innerHTML=`<div class="layerHead"><b>${esc(l.name)}</b><small>${l.type}</small></div><label>Nombre<input data-k="name" data-raw value="${esc(l.name)}"></label><div class="layerGrid"><label>X %<input data-k="x" type="number" value="${round(l.x*100)}"></label><label>Y %<input data-k="y" type="number" value="${round(l.y*100)}"></label><label>Ancho %<input data-k="width" type="number" value="${round(l.width*100)}"></label><label>Alto %<input data-k="height" type="number" value="${round(l.height*100)}"></label><label>Color<input data-k="color" data-raw type="color" value="${l.color}"></label><label>Opacidad %<input data-k="opacity" type="number" value="${round(l.opacity*100)}"></label><label>Tamaño texto %<input data-k="fontSize" type="number" value="${round(l.fontSize*100)}"></label><label>Rotación °<input data-k="rotation" data-raw type="number" value="${l.rotation||0}"></label></div>${textFields}${imageField}<button data-remove>Quitar</button>`;if(l.type==='text')d.querySelector('[data-k=textSlot]').value=l.textSlot;d.onclick=()=>{selected=l.id;renderLayers();drawAll()};d.querySelectorAll('[data-k]').forEach(i=>i.oninput=e=>{e.stopPropagation();l[i.dataset.k]=i.dataset.raw!==undefined?i.value:Number(i.value)/100;if(i.dataset.k==='rotation')l.rotation=Number(i.value);drawAll()});const f=d.querySelector('[data-file]');if(f)f.onchange=e=>{const file=e.target.files[0];if(!file||file.size>2_000_000)return alert('La imagen debe pesar menos de 2 MB');const reader=new FileReader();reader.onload=()=>{l.src=reader.result;drawAll()};reader.readAsDataURL(file)};d.querySelector('[data-remove]').onclick=e=>{e.stopPropagation();current.layers=current.layers.filter(x=>x.id!==l.id);selected=null;renderLayers();drawAll()};box.append(d)})}
for(const id of ['cfgName','cfgNetwork','cfgFormat','cfgStatus','cfgBackground'])$('#'+id).oninput=e=>{current[{cfgName:'name',cfgNetwork:'network',cfgFormat:'format',cfgStatus:'status',cfgBackground:'background'}[id]]=e.target.value;drawAll()};for(const k of ['Left','Top','Right','Bottom'])$('#safe'+k).oninput=e=>{current.safeArea[k.toLowerCase()]=Number(e.target.value)/100;drawAll()};
$$('[data-add]').forEach(b=>b.onclick=()=>{const type=b.dataset.add,id=crypto.randomUUID();current.layers.push({id,type,name:type==='text'?'Texto':'Nuevo '+type,x:.2,y:.2,width:.3,height:.12,color:'#ffffff',opacity:1,fontFamily:'Arial',fontWeight:'700',fontSize:.07,align:'left',textSlot:type==='text'?'literal':'literal',text:'Texto',strokeColor:'#000000',strokeWidth:0,spacing:.08,src:''});selected=id;renderLayers();drawAll()});
$('#new').onclick=()=>{current={name:'Perfil nuevo',network:'Personalizado',format:'square',status:'draft',background:'#101520',safeArea:{left:.1,top:.1,right:.1,bottom:.1},layers:[]};selected=null;fillConfig();drawAll()};
$('#duplicate').onclick=async()=>{if(!current.id)return alert('Guarda primero el perfil');await api(`/api/profiles/${current.id}/duplicate`,{method:'POST'});await load()};
$('#save').onclick=async()=>{try{let saved;if(current.id)saved=await api(`/api/profiles/${current.id}`,{method:'PUT',body:JSON.stringify(current)});else saved=await api('/api/profiles',{method:'POST',body:JSON.stringify(current)});await load(saved.id);notice('Perfil guardado')}catch(e){alert(e.message)}};
$('#delete').onclick=async()=>{if(!current.id||!confirm('¿Borrar este perfil?'))return;try{await api(`/api/profiles/${current.id}`,{method:'DELETE'});await load()}catch(e){alert(e.message)}};
$('#export').onclick=async()=>{render(canvas,ctx,{...current,format:$('#format').value},false);const dataUrl=canvas.toDataURL('image/png');try{await api('/api/exports',{method:'POST',body:JSON.stringify({profileId:current.id,dataUrl})});const a=document.createElement('a');a.href=dataUrl;a.download=`${current.name.replace(/[^a-z0-9]+/gi,'-').toLowerCase()}.png`;a.click();notice('PNG exportado');drawAll()}catch(e){alert(e.message)}};
function drag(c){let mode,start,base;c.onpointerdown=e=>{const p=point(c,e),l=current.layers.slice().reverse().find(l=>p.x>=l.x&&p.x<=l.x+l.width&&p.y>=l.y&&p.y<=l.y+l.height);if(!l)return;selected=l.id;mode=(Math.abs(p.x-(l.x+l.width))<.035&&Math.abs(p.y-(l.y+l.height))<.035)?'resize':'move';start=p;base={x:l.x,y:l.y,width:l.width,height:l.height};c.setPointerCapture(e.pointerId);renderLayers();drawAll()};c.onpointermove=e=>{if(!mode)return;const p=point(c,e),l=current.layers.find(x=>x.id===selected),dx=p.x-start.x,dy=p.y-start.y;if(mode==='move'){l.x=base.x+dx;l.y=base.y+dy}else{l.width=Math.max(.01,base.width+dx);l.height=Math.max(.01,base.height+dy)}drawAll()};c.onpointerup=()=>mode=null}drag(canvas);drag(cc);
const point=(c,e)=>{const r=c.getBoundingClientRect();return{x:(e.clientX-r.left)/r.width,y:(e.clientY-r.top)/r.height}};const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));const round=n=>Math.round(n*10)/10;const notice=s=>{$('#message').textContent=s;setTimeout(()=>$('#message').textContent='',2500)};
async function load(preferred){try{await api('/api/session');profiles=await api('/api/profiles');$('#profile').innerHTML=profiles.filter(p=>p.status!=='archived').map(p=>`<option value="${p.id}">${esc(p.name)} · ${p.status}</option>`).join('');selectProfile(preferred||profiles[0]?.id)}catch(e){document.querySelector('main').innerHTML=`<div class="stage"><h2>${esc(e.message)}</h2><p>Usa una cuenta habilitada en la esquina superior derecha.</p></div>`}}load();
