const productCopy = {
  ops: {
    es: {
      pageLabel: "Avia OPS", navLines: "Líneas de negocio", navOps: "Avia OPS", navIntelligence: "Avia Intelligence", navLabs: "Avia Labs", navContact: "Contacto", navCta: "Agendar demo",
      kicker: "Avia OPS", title: "OPS · Automatización operacional", description: "OPS monitorea procesos, detecta cambios, ordena estados y entrega reportes accionables para operar con menos trabajo manual y más control.", primary: "Entrar al dashboard", secondary: "Solicitar demo",
      badge1: "Seguimiento automático", badge2: "Alertas operativas", badge3: "Historial trazable", panelTitle: "OPS DASHBOARD", panelSmall: "Automatización operacional",
      kpi1: "Procesos", kpi2: "Con cambios", kpi3: "Alertas", kpi4: "Errores", eventTitle: "Eventos detectados", row1: "Proceso actualizado", row1s: "Nueva variación registrada", row2: "Alerta generada", row2s: "Requiere revisión", row3: "Historial guardado", row3s: "Comparación disponible", status1: "Cambio", status2: "Alerta", status3: "OK", summary: "Resumen",
      sectionEyebrow: "Producto", sectionTitle: "Qué hace OPS", sectionText: "OPS convierte revisión manual dispersa en un flujo operativo con evidencia, estado y acción siguiente.", f1: "Monitorea", f1t: "Consulta fuentes, guarda resultados y mantiene un historial para comparar cambios reales.", f2: "Detecta", f2t: "Identifica variaciones relevantes, nuevos eventos, estados y errores de consulta.", f3: "Reporta", f3t: "Entrega emails, dashboards e informes con resumen ejecutivo y detalle accionable.",
      stepEyebrow: "Operación", stepTitle: "Flujo de trabajo", s1: "Configurar", s1t: "Se cargan usuarios, procesos y reglas de revisión.", s2: "Ejecutar", s2t: "OPS consulta, registra y compara resultados.", s3: "Alertar", s3t: "El sistema clasifica cambios y notifica al equipo.", s4: "Auditar", s4t: "El historial queda disponible para seguimiento y control.",
      th1: "Módulo", th2: "Función", th3: "Salida", tr1a: "Motor de revisión", tr1b: "Consulta y normaliza información", tr1c: "Snapshot trazable", tr2a: "Detector de cambios", tr2b: "Compara estado anterior y nuevo", tr2c: "Alerta clasificada", tr3a: "Reporte", tr3b: "Resume hallazgos y acciones", tr3c: "Email / dashboard / informe", ctaTitle: "Automatiza la operación.", footer: "Build. Connect. Launch."
    },
    en: {
      pageLabel: "Avia OPS", navLines: "Business lines", navOps: "Avia OPS", navIntelligence: "Avia Intelligence", navLabs: "Avia Labs", navContact: "Contact", navCta: "Schedule demo",
      kicker: "Avia OPS", title: "OPS · Operational automation", description: "OPS monitors processes, detects changes, organizes statuses and delivers actionable reports so teams operate with less manual work and more control.", primary: "Enter dashboard", secondary: "Request demo",
      badge1: "Automatic tracking", badge2: "Operational alerts", badge3: "Traceable history", panelTitle: "OPS DASHBOARD", panelSmall: "Operational automation",
      kpi1: "Processes", kpi2: "Changed", kpi3: "Alerts", kpi4: "Errors", eventTitle: "Detected events", row1: "Updated process", row1s: "New variation registered", row2: "Generated alert", row2s: "Requires review", row3: "History saved", row3s: "Comparison available", status1: "Change", status2: "Alert", status3: "OK", summary: "Summary",
      sectionEyebrow: "Product", sectionTitle: "What OPS does", sectionText: "OPS turns scattered manual review into an operational workflow with evidence, status and next action.", f1: "Monitors", f1t: "Queries sources, saves results and keeps a history to compare real changes.", f2: "Detects", f2t: "Identifies relevant variations, new events, statuses and query errors.", f3: "Reports", f3t: "Delivers emails, dashboards and reports with executive summary and actionable detail.",
      stepEyebrow: "Operations", stepTitle: "Workflow", s1: "Configure", s1t: "Users, processes and review rules are loaded.", s2: "Run", s2t: "OPS queries, records and compares results.", s3: "Alert", s3t: "The system classifies changes and notifies the team.", s4: "Audit", s4t: "History remains available for tracking and control.",
      th1: "Module", th2: "Function", th3: "Output", tr1a: "Review engine", tr1b: "Queries and normalizes information", tr1c: "Traceable snapshot", tr2a: "Change detector", tr2b: "Compares previous and new state", tr2c: "Classified alert", tr3a: "Report", tr3b: "Summarizes findings and actions", tr3c: "Email / dashboard / report", ctaTitle: "Automate operations.", footer: "Build. Connect. Launch."
    }
  },
  intelligence: {
    es: { pageLabel: "Avia Intelligence", navLines: "Líneas de negocio", navOps: "Avia OPS", navIntelligence: "Avia Intelligence", navLabs: "Avia Labs", navContact: "Contacto", navCta: "Agendar demo", kicker: "Avia Intelligence", title: "Riesgo y datos convertidos en decisión.", description: "Avia Intelligence toma información dispersa, la estructura y la transforma en señales, reportes y tableros para evaluar riesgo, priorizar acciones y operar con criterio.", primary: "Solicitar diagnóstico", secondary: "Ver Avia Labs", badge1: "Riesgo y datos", badge2: "Dashboards ejecutivos", badge3: "Señales accionables", panelTitle: "INTELLIGENCE BOARD", panelSmall: "Riesgo y datos", kpi1: "Fuentes", kpi2: "Riesgos", kpi3: "Modelos", kpi4: "Alertas", eventTitle: "Señales priorizadas", row1: "Riesgo alto", row1s: "Requiere validación", row2: "Dato inconsistente", row2s: "Fuente por revisar", row3: "Señal positiva", row3s: "Criterio aprobado", status1: "Prioridad", status2: "Dato", status3: "OK", summary: "Score", sectionEyebrow: "Producto", sectionTitle: "Qué hace Avia Intelligence", sectionText: "Ordena datos, calcula señales y entrega reportes que ayudan a decidir con evidencia.", f1: "Integra datos", f1t: "Conecta fuentes internas, planillas, APIs, bases de datos y registros operativos.", f2: "Modela riesgo", f2t: "Construye reglas, criterios y scores para clasificar señales relevantes.", f3: "Comunica decisión", f3t: "Entrega tableros, reportes y alertas con foco en acción siguiente.", stepEyebrow: "Casos de uso", stepTitle: "Dónde aplica", s1: "Riesgo comercial", s1t: "Evaluación de señales para clientes, proveedores o personas.", s2: "Control financiero", s2t: "Seguimiento de datos, excepciones, saldos y desviaciones.", s3: "Operación legal", s3t: "Priorización de carteras, estados y cambios relevantes.", s4: "Dirección ejecutiva", s4t: "Tableros con visión de riesgo, avance y foco operativo.", th1: "Capa", th2: "Función", th3: "Salida", tr1a: "Datos", tr1b: "Consolidación y limpieza", tr1c: "Base confiable", tr2a: "Modelo", tr2b: "Reglas, score y clasificación", tr2c: "Riesgo priorizado", tr3a: "Reporte", tr3b: "Visualización y narrativa ejecutiva", tr3c: "Dashboard / informe", ctaTitle: "Convierte datos en criterio.", footer: "Build. Connect. Launch." },
    en: { pageLabel: "Avia Intelligence", navLines: "Business lines", navOps: "Avia OPS", navIntelligence: "Avia Intelligence", navLabs: "Avia Labs", navContact: "Contact", navCta: "Schedule demo", kicker: "Avia Intelligence", title: "Risk and data turned into decisions.", description: "Avia Intelligence takes scattered information, structures it and turns it into signals, reports and dashboards to evaluate risk, prioritize actions and operate with judgment.", primary: "Request diagnosis", secondary: "View Avia Labs", badge1: "Risk and data", badge2: "Executive dashboards", badge3: "Actionable signals", panelTitle: "INTELLIGENCE BOARD", panelSmall: "Risk and data", kpi1: "Sources", kpi2: "Risks", kpi3: "Models", kpi4: "Alerts", eventTitle: "Prioritized signals", row1: "High risk", row1s: "Requires validation", row2: "Inconsistent data", row2s: "Source to review", row3: "Positive signal", row3s: "Criteria approved", status1: "Priority", status2: "Data", status3: "OK", summary: "Score", sectionEyebrow: "Product", sectionTitle: "What Avia Intelligence does", sectionText: "It organizes data, calculates signals and delivers reports that help teams decide with evidence.", f1: "Integrates data", f1t: "Connects internal sources, spreadsheets, APIs, databases and operational records.", f2: "Models risk", f2t: "Builds rules, criteria and scores to classify relevant signals.", f3: "Communicates decisions", f3t: "Delivers dashboards, reports and alerts focused on the next action.", stepEyebrow: "Use cases", stepTitle: "Where it applies", s1: "Commercial risk", s1t: "Signal evaluation for clients, suppliers or people.", s2: "Financial control", s2t: "Tracking data, exceptions, balances and deviations.", s3: "Legal operations", s3t: "Prioritizing portfolios, statuses and relevant changes.", s4: "Executive direction", s4t: "Dashboards with risk, progress and operational focus.", th1: "Layer", th2: "Function", th3: "Output", tr1a: "Data", tr1b: "Consolidation and cleaning", tr1c: "Reliable base", tr2a: "Model", tr2b: "Rules, score and classification", tr2c: "Prioritized risk", tr3a: "Report", tr3b: "Visualization and executive narrative", tr3c: "Dashboard / report", ctaTitle: "Turn data into judgment.", footer: "Build. Connect. Launch." }
  },
  labs: {
    es: { pageLabel: "Avia Labs", navLines: "Líneas de negocio", navOps: "Avia OPS", navIntelligence: "Avia Intelligence", navLabs: "Avia Labs", navContact: "Contacto", navCta: "Agendar demo", kicker: "Avia Labs", title: "APIs y apps conectadas a la operación real.", description: "Avia Labs construye herramientas digitales a medida: APIs, dashboards, automatizaciones, apps internas e integraciones que convierten procesos manuales en sistemas utilizables.", primary: "Conversar proyecto", secondary: "Ver Avia OPS", badge1: "APIs", badge2: "Apps internas", badge3: "Integraciones", panelTitle: "LABS BUILDER", panelSmall: "APIs · Apps · Integraciones", kpi1: "APIs", kpi2: "Apps", kpi3: "Jobs", kpi4: "Uptime", eventTitle: "Integraciones activas", row1: "Endpoint operativo", row1s: "Consulta y respuesta normalizada", row2: "Base conectada", row2s: "Lectura y escritura segura", row3: "Interfaz interna", row3s: "Flujo listo para usuarios", status1: "Live", status2: "OK", status3: "Build", summary: "Deploy", sectionEyebrow: "Producto", sectionTitle: "Qué construye Avia Labs", sectionText: "Desarrolla herramientas digitales específicas para resolver procesos internos que no calzan bien en software genérico.", f1: "APIs", f1t: "Servicios para conectar bases, sitios, herramientas externas y procesos internos.", f2: "Apps", f2t: "Interfaces web o móviles para capturar datos, ejecutar procesos y consultar información.", f3: "Automatizaciones", f3t: "Jobs, bots y flujos programados que reducen trabajo repetitivo y errores manuales.", stepEyebrow: "Metodología", stepTitle: "Cómo se construye", s1: "Mapear", s1t: "Se entiende el proceso, las fuentes y el usuario final.", s2: "Diseñar", s2t: "Se define arquitectura, datos, pantallas y endpoints.", s3: "Construir", s3t: "Se desarrolla una versión usable conectada a la operación.", s4: "Escalar", s4t: "Se agregan permisos, métricas, logs y mejoras.", th1: "Tipo", th2: "Ejemplo", th3: "Salida", tr1a: "API", tr1b: "Conector entre sistema externo y base interna", tr1c: "Endpoint documentado", tr2a: "App", tr2b: "Panel operativo para usuarios o clientes", tr2c: "Web app responsive", tr3a: "Automatización", tr3b: "Proceso programado, alerta o bot", tr3c: "Job operativo", ctaTitle: "Construye la herramienta que tu operación necesita.", footer: "Build. Connect. Launch." },
    en: { pageLabel: "Avia Labs", navLines: "Business lines", navOps: "Avia OPS", navIntelligence: "Avia Intelligence", navLabs: "Avia Labs", navContact: "Contact", navCta: "Schedule demo", kicker: "Avia Labs", title: "APIs and apps connected to real operations.", description: "Avia Labs builds custom digital tools: APIs, dashboards, automations, internal apps and integrations that turn manual processes into usable systems.", primary: "Discuss project", secondary: "View Avia OPS", badge1: "APIs", badge2: "Internal apps", badge3: "Integrations", panelTitle: "LABS BUILDER", panelSmall: "APIs · Apps · Integrations", kpi1: "APIs", kpi2: "Apps", kpi3: "Jobs", kpi4: "Uptime", eventTitle: "Active integrations", row1: "Operational endpoint", row1s: "Normalized request and response", row2: "Connected database", row2s: "Safe read and write", row3: "Internal interface", row3s: "Flow ready for users", status1: "Live", status2: "OK", status3: "Build", summary: "Deploy", sectionEyebrow: "Product", sectionTitle: "What Avia Labs builds", sectionText: "It develops specific digital tools to solve internal processes that do not fit well into generic software.", f1: "APIs", f1t: "Services to connect databases, sites, external tools and internal processes.", f2: "Apps", f2t: "Web or mobile interfaces to capture data, run processes and query information.", f3: "Automations", f3t: "Jobs, bots and scheduled flows that reduce repetitive work and manual errors.", stepEyebrow: "Method", stepTitle: "How it is built", s1: "Map", s1t: "The process, sources and final user are understood.", s2: "Design", s2t: "Architecture, data, screens and endpoints are defined.", s3: "Build", s3t: "A usable version connected to operations is developed.", s4: "Scale", s4t: "Permissions, metrics, logs and improvements are added.", th1: "Type", th2: "Example", th3: "Output", tr1a: "API", tr1b: "Connector between external system and internal database", tr1c: "Documented endpoint", tr2a: "App", tr2b: "Operational panel for users or clients", tr2c: "Responsive web app", tr3a: "Automation", tr3b: "Scheduled process, alert or bot", tr3c: "Operational job", ctaTitle: "Build the tool your operation needs.", footer: "Build. Connect. Launch." }
  }
};

function applyProductLang(lang) {
  const page = document.body.dataset.product || "ops";
  const selected = lang === "en" ? "en" : "es";
  const dict = productCopy[page]?.[selected];
  if (!dict) return;
  document.documentElement.lang = selected;
  localStorage.setItem("avia-lang", selected);
  document.querySelectorAll("[data-pi18n]").forEach((node) => {
    const key = node.getAttribute("data-pi18n");
    if (dict[key]) node.textContent = dict[key];
  });
  const btn = document.getElementById("product-lang-toggle");
  if (btn) btn.textContent = selected === "es" ? "EN" : "ES";
}

const productLangButton = document.getElementById("product-lang-toggle");
if (productLangButton) productLangButton.addEventListener("click", () => applyProductLang(document.documentElement.lang === "es" ? "en" : "es"));
applyProductLang(localStorage.getItem("avia-lang") || document.documentElement.lang || "es");
